<%@ Page Title="" Language="C#" MasterPageFile="~/PrisonMaster.Master" AutoEventWireup="true" CodeBehind="admindashboard.aspx.cs" Inherits="Prison.admindashboard" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            margin-left: 87px;
        }
    </style>
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


     <div class="dash">

    
           <div class="sidenav">

                <nav class="nav"> 
                      
                    <asp:Button class="a" Text="Prisoners" runat="server" ID="btnPrisoner" OnClick="btnPrisoner_Click" />
                    <asp:Button class="a" Text="Staff" runat="server" ID="btnStaff" OnClick="btnStaff_Click" />
                     <asp:Button class="a" Text="Admin" runat="server" ID="btnAdmin" />
                      
                    
                </nav>
 
            </div>
           
          

 <div class="mainnav">

     <div class="admin_dash">
         <div class="left">
            <h2>Hello Admin </h2>
            <h3>Welcome To The Dashboard</h3>
         </div>

         <div class="right">
             
            <asp:Button ID="btnAddNewPrisoner" class="button_add" runat="server" Text="Add New Prisoner" OnClick="btnAddNewPrisoner_Click" BackColor="#66CCFF" />
             
             
             <asp:Button ID="btnAddNewStaff" class="button_add" runat="server" OnClick="btnAddNewStaff_Click" Text="Add New Staff" BackColor="#66FF66"/>

             <asp:Button ID="btnLogOut" CssClass="button_add" runat="server" OnClick="btnLogOut_Click" Text="LogOut " BackColor="#999966"/>

          

               

               
                 
         </div>
        
     </div>
   
     <br />
     <br />
     <br />
     <br />


     <div>
                     
                  <asp:Label ID="Label1"  runat="server" Text="Label">Find Prisoner by Id: </asp:Label>
                  <asp:TextBox ID="txtSearch" runat="server"></asp:TextBox>
                 <input type="submit" name="name" value="Search" />


                 <asp:GridView runat="server" EmptyDataText="No Records Found" ShowHeaderWhenEmpty="True" AutoGenerateColumns="False" Height="100px" Width="1000px" CellSpacing="1" DataSourceID="SqlDataSource3" CssClass="auto-style1">
                     <Columns>
                         <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                         <asp:BoundField DataField="crime" HeaderText="crime" SortExpression="crime" />
                         <asp:BoundField DataField="date_jailed" HeaderText="date_jailed" SortExpression="date_jailed" />
                         <asp:BoundField DataField="sentence" HeaderText="sentence" SortExpression="sentence" />
                         <asp:BoundField DataField="kin_contact" HeaderText="kin_contact" SortExpression="kin_contact" />
                     </Columns>
                     

                 </asp:GridView>


                  <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:PrisonConnectionString %>" SelectCommand="SELECT [Name], [crime], [date_jailed], [sentence], [kin_contact] FROM [Prisoner] WHERE ([Id] = @Id)">
                      <SelectParameters>
                          <asp:ControlParameter ControlID="txtSearch" Name="Id" PropertyName="Text" Type="Int32" />
                      </SelectParameters>
                  </asp:SqlDataSource>
             </div>
     
     <p>

         
    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource2" Height="250px" Width="1000px" CellSpacing="2" HorizontalAlign="Center" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True" AllowSorting="True" EnableSortingAndPagingCallbacks="True" PageSize="5">
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="crime" HeaderText="crime" SortExpression="crime" />
            <asp:BoundField DataField="sentence" HeaderText="sentence" SortExpression="sentence" />
            <asp:BoundField DataField="date_jailed" HeaderText="date_jailed" SortExpression="date_jailed" />
          

            
        
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:PrisonConnectionString %>" SelectCommand="SELECT Id, Name, crime, sentence, date_jailed FROM Prisoner ORDER BY Id" UpdateCommand="Update [Prisoner] Set [Name] = @Name, [sentence] = @sentence where [id] = @id" DeleteCommand ="DELETE FROM [Prisoner] where [id] = @id"></asp:SqlDataSource>
        </p>
      <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="Employee_Id" DataSourceID="SqlDataSource1" Height="250px" Width="1000px" CellSpacing="2" HorizontalAlign="Center" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True" AllowSorting="True" PageSize="5">
            <Columns>
                <asp:BoundField DataField="Employee_Id" HeaderText="Employee_Id" ReadOnly="True" SortExpression="Employee_Id" />
                <asp:BoundField DataField="firstName" HeaderText="firstName" SortExpression="firstName" />
                <asp:BoundField DataField="lastName" HeaderText="lastName" SortExpression="lastName" />
                <asp:BoundField DataField="phoneNumber" HeaderText="phoneNumber" SortExpression="phoneNumber" />
                <asp:BoundField DataField="role_id" HeaderText="role_id" SortExpression="role_id" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PrisonConnectionString %>" SelectCommand="SELECT [Employee_Id], [firstName], [lastName], [phoneNumber], [role_id] FROM [Staff] ORDER BY [Employee_Id]" UpdateCommand="Update [Staff] Set [firstName] = @firstName, [lastName] = @lastName, [phoneNumber] = @phoneNumber where [employee_Id] = @employee_Id " DeleteCommand ="DELETE FROM [Staff] where [employee_Id] = @employee_Id"></asp:SqlDataSource>
        <br />
    </div>
        </div>

   

   

   
  
</asp:Content>
