<%@ Page Title="" Language="C#" MasterPageFile="~/PrisonMaster.Master" AutoEventWireup="true" CodeBehind="wardendashboard.aspx.cs" Inherits="Prison.wardendashboard" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 170px;
            height: 100vh; //;
            background-color: rgb(132,86,254);
            background-color: rgb(26,140,216);
            position: fixed;
            float: left;
            font-family: 'Times New Roman';
            left: 1px;
            top: 121px;
        }
    </style>
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    

     
    <div class="dash">

        

    
           <div class="sidenav">

                <nav class="nav"> 
                      
                    <asp:Button class="a" Text="Prisoners" runat="server" ID="btnPrisoner" OnClick="btnPrisoner_Click" />
                      <asp:Button class="a" Text="Rooms" runat="server" ID="btnRoom" OnClick="btnRoom_Click"/>      
                    
                </nav>
 
            </div>
          <div class="mainnav">

              <div class="left">
            <h2>Hello Warden/Guard&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              

               
                  <asp:Button ID="btnLogOut" CssClass="button_add" runat="server" OnClick="btnLogOut_Click" Text="Sign Out " BackColor="#66CCFF"/>
                  </h2>
            <h3>Welcome To The Guard Dashboard</h3>

           
                  <h3>&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;
                      &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
                      <asp:Label Text="PRISONERS ROOM ALLOCATION" runat="server" ID="lblRoom" /></h3>
               
                 
         </div>

              
              
             
              
           
           <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="room_number" DataSourceID="SqlDataSource1" Height="250px" Width="1000px" CellSpacing="2" HorizontalAlign="Center" AllowPaging="True" AllowSorting="True" PageSize="5">
               <Columns>
                   <asp:CommandField ShowSelectButton="True" />
                   <asp:BoundField DataField="room_number" HeaderText="room_number" ReadOnly="True" SortExpression="room_number" />
                   <asp:BoundField DataField="prisoner1_id" HeaderText="prisoner1_id" SortExpression="prisoner1_id" />
                   <asp:BoundField DataField="prisoner2_id" HeaderText="prisoner2_id" SortExpression="prisoner2_id" />
                   <asp:BoundField DataField="prisoner3_id" HeaderText="prisoner3_id" SortExpression="prisoner3_id" />
                   <asp:BoundField DataField="prisoner4_id" HeaderText="prisoner4_id" SortExpression="prisoner4_id" />
               </Columns>
           </asp:GridView>

              <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PrisonConnectionString %>" SelectCommand="SELECT [room_number], [prisoner1_id], [prisoner2_id], [prisoner3_id], [prisoner4_id] FROM [Rooms] ORDER BY [room_number]" UpdateCommand="Update [Rooms] Set [prisoner1_id] = @prisoner1_id, [prisoner2_id] = @prisoner2_id, [prisoner3_id] = @prisoner3_id, [prisoner4_id] = @prisoner4_id where [room_number] = @room_number " DeleteCommand ="DELETE FROM [Rooms] where [room_number] = @room_number"></asp:SqlDataSource> >

              <br />
             

              <div class="left">
                
                 
                     
                     
                  <h3> &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
                       &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
                       &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
                       &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;
                      <asp:Label Text="LIST OF PRISONERS IN VANARA" runat="server" ID="lblPrisoners" /></h3> 
              </div>
              
                     
                  

              <asp:GridView ID="GridView2" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="SqlDataSource2" PageSize="5" Height="250px" Width="1000px" CellSpacing="2" HorizontalAlign="Center">
                  <Columns>
                      <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" />
                      <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                      <asp:BoundField DataField="crime" HeaderText="crime" SortExpression="crime" />
                      <asp:BoundField DataField="date_jailed" HeaderText="date_jailed" SortExpression="date_jailed" />
                      <asp:BoundField DataField="sentence" HeaderText="sentence" SortExpression="sentence" />
                      <asp:BoundField DataField="kin_contact" HeaderText="kin_contact" SortExpression="kin_contact" />
                  </Columns>
              </asp:GridView>
              <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:PrisonConnectionString %>" SelectCommand="SELECT [Id], [Name], [crime], [date_jailed], [sentence], [kin_contact] FROM [Prisoner] ORDER BY [Id]"></asp:SqlDataSource>
           

              <br />
              <br />
              <br />
        </div>     

             </div> 
                 
</asp:Content>
